remote_theme: chrisrhymes/bulma-clean-theme
title: Frictionless Enterprise
author: Phil Wainewright
email: pw@pcxvs.com
description: A blueprint for digitally connected business - by Phil Wainewright

# Pagination settings
paginate: 5
paginate_path: "blog/page:num"

# identity settings
twitter_username: philww # DO NOT include the @ character, or else the build will fail!
github_username:  philww241 # DO NOT include the @ character, or else the build will fail!
google_analytics: UA-169369903-1

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true # set to false to remove sidebar excerpts 
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Phil Wainewright"
      show_sidebar: true # set to false to remove sidebar excerpts 
      hide_share_buttons: true # set to false to reveal social share buttons
      
